variables:
  CONAN_USER_HOME: "$CI_PROJECT_DIR"
  desktop_only: 'true'

stages:
  - build

before_script:
  - cmake --version
  - conan --version
  - conan remote add conan https://api.bintray.com/conan/stever/conan

android:
  image: registry.gitlab.com/ssrobins/docker-android-build
  stage: build
  script:
    - lscpu
    - cat /proc/meminfo | grep MemTotal
    - java -version
    - ./build_android.sh
    - cd build_android
    - mkdir _package
    - find . -name \*.apk -exec mv {} _package/ \;
  artifacts:
    paths:
      - build_android/_package/*.apk
  except:
    variables:
      - $desktop_only == "true"

ios:
  stage: build
  script:
    - ./build_ios.sh
  tags:
    - ios
  except:
    variables:
      - $desktop_only == "true"

ios-sim:
  stage: build
  script:
    - ./build_ios_sim.sh
  tags:
    - ios
  except:
    variables:
      - $desktop_only == "true"

linux:
  image: registry.gitlab.com/ssrobins/docker-linux-build
  stage: build
  script:
    - lscpu
    - cat /proc/meminfo | grep MemTotal
    - gcc --version
    - ./build_linux.sh
  artifacts:
    paths:
      - build_linux/_package/*.tar.gz

mac:
  stage: build
  script:
    - ./build_mac.sh
  artifacts:
    paths:
      - build_mac/_package/*.zip
  tags:
    - mac

windows:
  stage: build
  script:
    - build_windows.bat
  artifacts:
    paths:
      - build_windows/_package/*.zip
  tags:
    - windows

windows64:
  stage: build
  script:
    - build_windows64.bat
  artifacts:
    paths:
      - build_windows64/_package/*.zip
  tags:
    - windows
